export const FEATURE_METADATA_KEY = 'feature_flag_name';

export const FEATURE_FLAGS_JSON_ENV = 'FEATURE_FLAGS_JSON';
export const FEATURE_FLAGS_DISABLED_STATUS_ENV = 'FEATURE_FLAGS_DISABLED_STATUS';
